# Introduction to Numpy and Numba
NumPy is the fundamental package for scientific computing with Python. It contains among other things:

- a powerful N-dimensional array object
- tools for integrating C/C++ and Fortran code
- useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

## Numpy Arrays

In [1]:
# We always import Numpy as follows in order not to pollute the namespace
import numpy as np

In [2]:
# central to Numpy is a special array type 
# to create it we passs a Python list
v = np.array([1,2,3,4])
print(v)

[1 2 3 4]


In [3]:
# We can also pass in a 2 dimensional Python list to create a 2D array
m = np.array([[1, 2, 5], [4, 3, 4]])
print(m)

[[1 2 5]
 [4 3 4]]


In [4]:
print(type(m)) 

<class 'numpy.ndarray'>


In [5]:
v.shape

(4,)

In [6]:
m.shape

(2, 3)

In [7]:
v.size

4

In [8]:
m.size

6

In [9]:
# Accessing is same as in Python arrays
m[1][2]

4

In [10]:
# But we can ALSO access the elements using a shorter notation
m[1,2]

4

In [11]:
# We can change the shape of an array
v.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [12]:
# We can create large arrays of zeros
z = np.zeros(100)

In [13]:
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


In [14]:
# We can add some shape to the matrix using a tuple containing the number of rows and columns
z = np.zeros((5,10))
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [15]:
# If we want to start with ones
z = np.ones(20)
print(z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [16]:
z = np.ones((5,4))
print(z)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Indexing and Broadcasting

We can index arrays

In [17]:
v = np.array([12,22,13,44,22,43,35,36])

In [18]:
v[0]

12

In [19]:
v[2:5]

array([13, 44, 22])

In [20]:
v[5:]

array([43, 35, 36])

In [21]:
v[5:-1]

array([43, 35])

In [22]:
v[1:4] = 100

In [23]:
v

array([ 12, 100, 100, 100,  22,  43,  35,  36])

## Arange

In [24]:
# Numpy has its own range function called arange
l = np.arange(10)
print(l)

[0 1 2 3 4 5 6 7 8 9]


In [25]:
# We can shuffle the order of the array - note that shuffle changes it
np.random.shuffle(l)
print(l)

[7 0 2 5 4 9 8 6 3 1]


## Linspace

In [26]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## Element-wise Array Functions
Standard mathematical operations act on the elements of an array

In [27]:
# Create a matrix to begin with
m = np.array([[4,2,6],[9,4,6],[2,3,1]])
print(m)

[[4 2 6]
 [9 4 6]
 [2 3 1]]


In [28]:
# Extracting sub arrays - extract all in column 3 (2 == column 3)
m[:,2]

array([6, 6, 1])

In [29]:
# Extracting sub arrays - extract all in row 3 (1 == row 2)
m[1,:]

array([9, 4, 6])

In [30]:
print(m*2)

[[ 8  4 12]
 [18  8 12]
 [ 4  6  2]]


In [31]:
# This is NOT matrix multiplication. It is elementwise squaring
print(m*m)

[[16  4 36]
 [81 16 36]
 [ 4  9  1]]


In [32]:
# Can do elementwise tests that return booleans
c = m > 3.0
print(c)

[[ True False  True]
 [ True  True  True]
 [False False False]]


## Matrix Operations

In [33]:
# Create an identity matrix that must be a square matrix
i = np.identity(5)
print(i)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [34]:
m=np.array([[2,3],[1,4]])

In [35]:
# Transpose of a matrix is when columns and rows are swapped
print(m.T)

[[2 1]
 [3 4]]


In [36]:
# Matrix multiplication m x m
m.dot(m)

array([[ 7, 18],
       [ 6, 19]])

In [37]:
# Average
m.mean()

2.5

In [38]:
# Variance
m.var()

1.25

In [39]:
# Calculate matrix inverse 
inv = np.linalg.inv(m)

In [40]:
# Check that this gives the identity when multiplied 
inv.dot(m)

array([[1., 0.],
       [0., 1.]])

## Random Numbers in Numpy

In [41]:
np.random.randint(1,100)

97

In [42]:
np.random.seed(1929)

In [43]:
x=np.random.rand(10)

In [44]:
x

array([0.36960996, 0.22563543, 0.21721826, 0.48176578, 0.71151956,
       0.90325038, 0.04534301, 0.849436  , 0.18603901, 0.60684882])

In [45]:
# uniform random numbers in [0,1]
r=np.random.rand(5,5)
print(r)

[[0.6390298  0.30023985 0.48945367 0.79963662 0.19031583]
 [0.06958461 0.10054818 0.85463787 0.1797611  0.35232879]
 [0.7572909  0.89452035 0.78275925 0.6844623  0.75584773]
 [0.73743876 0.41510796 0.00344385 0.92024923 0.23828034]
 [0.33168693 0.83037913 0.64791143 0.21747986 0.25233504]]


In [46]:
# Gaussian random numbers 
r=np.random.normal(size=(5,5))
print(r)

[[ 0.31283602 -1.55114371 -3.99666151  0.71636619 -1.12403472]
 [ 0.39412402 -1.92346252 -1.16413746  1.28124733 -0.73497848]
 [-1.88965265  0.90429013 -0.04935378  0.48400485  0.37292679]
 [ 0.17975186 -1.74221404 -0.42921896  0.10769077  0.60904049]
 [ 1.19274869 -0.58127017  0.25608102  0.93267263  0.98269671]]


## Vectorized Calculations

In [47]:
x = np.random.rand(10)
y = np.exp(x)
print(y)

[2.41722271 1.78365694 1.51419373 1.48902598 1.46532101 1.86230581
 2.39910151 1.932834   1.01920128 1.84898872]


In [48]:
import timeit

In [49]:
# Do not use Python math functions with Numpy - this fails
from math import exp

In [50]:
numElements = 10000
rarray=np.random.rand(numElements)

In [51]:
def f1(rv):
    x=[]
    for r in rarray: x.append(exp(r))
    return x

In [52]:
%timeit x = f1(rarray)

2.45 ms ± 98.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


A ms is a thousandth of a second

In [53]:
t1 = 2.61 * 0.001

In [54]:
x = f1(rarray)

In [55]:
def f2(rv):
    x=np.exp(rv)
    return x

In [56]:
%timeit x = f2(rarray)

59.3 µs ± 752 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


A $\mu$ second is a millionth of a second

In [57]:
t2 = 60 * 0.000001

In [58]:
x = f2(rarray)

In [59]:
print(x[2929])

1.0854485386072579


In [60]:
t1/t2

43.5

I get a factor of improvement of about 43

# Numba

In [61]:
from numba import njit

In [62]:
@njit
def f3(rv):
    x = []
    for r in rv: 
        x.append(exp(r))
 
    return x

In [63]:
%timeit x = f3(rarray)

215 µs ± 53.8 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [64]:
print(x[2929])

1.0854485386072579


In [65]:
t3 = 254*0.000001

In [66]:
print("Basic Python %9.5f ms" %(t1*1000000))
print("Numpy Python %9.5f ms" %(t2*1000000))
print("Numba Python %9.5f ms" %(t3*1000000))

Basic Python 2610.00000 ms
Numpy Python  60.00000 ms
Numba Python 254.00000 ms


## Using Numba if the function cannot be vectorized

In [67]:
from numba import njit

In [68]:
def basicSort1(x):
    n = len(x)
    ordered = False
    
    while ordered == False:
        ordered = True

        for i in range(0,n-1):
            if x[i+1] < x[i]:
                a = x[i]
                x[i] = x[i+1]
                x[i+1] = a
                ordered = False
    
    return x

In [69]:
@njit 
def basicSort2(x):
    n = len(x)
    ordered = False
    
    while ordered == False:
        ordered = True

        for i in range(0,n-1):
            if x[i+1] < x[i]:
                a = x[i]
                x[i] = x[i+1]
                x[i+1] = a
                ordered = False
                
    return x

In [70]:
# Do not make this too large as computational time scales as this squared
numElements = 5000

Create a randomly sorted list

In [71]:
v = np.arange(0,numElements)
np.random.shuffle(v)
print(v)

[2389 3986 1079 ... 4226 3914 1376]


Now see how quickly we can sort it in Python

In [72]:
%timeit basicSort1(v);

1.22 ms ± 116 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


Check that it is sorted

In [73]:
print(v)

[   0    1    2 ... 4997 4998 4999]


Generate another random list

In [74]:
v = np.arange(0,numElements)
np.random.shuffle(v)
print(v)

[4029  211 4942 ... 2127 2191  431]


In [75]:
%timeit basicSort2(v);

10.2 µs ± 2.15 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [76]:
print(v)

[   0    1    2 ... 4997 4998 4999]


In [77]:
(1.65*0.001)/(10.3*0.000001)

160.19417475728156

Once again we get a big speed up